# Generated by Django 5.0.4 on 2024-05-20 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomBatiment', models.CharField(max_length=500)),
                ('typeBatiment', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'Batiment',
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('etat', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], default='ON', max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('categorie', models.CharField(blank=True, max_length=500, null=True)),
                ('puissance', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1', models.FloatField()),
                ('column2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('dateAlerte', models.DateTimeField(blank=True, null=True)),
                ('valeur', models.FloatField(blank=True, null=True)),
                ('notifie', models.BooleanField(default=False)),
                ('vu', models.BooleanField(default=False)),
                ('userID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipementId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.equipement')),
            ],
        ),
        migrations.CreateModel(
            name='Etage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.FloatField(blank=True, null=True)),
                ('nomEtage', models.CharField(blank=True, max_length=500, null=True)),
                ('batimentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.batiment')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodeActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempsDebut', models.DateTimeField()),
                ('tempsFin', models.DateTimeField(blank=True, null=True)),
                ('consommation', models.FloatField(blank=True, null=True)),
                ('Equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.equipement')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=30)),
                ('userId', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causes', models.CharField(blank=True, max_length=2000, null=True)),
                ('solutions', models.CharField(blank=True, max_length=2000, null=True)),
                ('risques', models.CharField(blank=True, max_length=2000, null=True)),
                ('equipementsDemandes', models.CharField(blank=True, max_length=2000, null=True)),
                ('equipementsNecessites', models.CharField(blank=True, max_length=2000, null=True)),
                ('dateRapport', models.DateTimeField(blank=True, null=True)),
                ('vu', models.BooleanField(default=False)),
                ('notifie', models.BooleanField(default=False)),
                ('alerte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.alerte')),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.equipement')),
                ('redacteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateTimeField(auto_now_add=True, null=True)),
                ('dateFin', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, max_length=2000, null=True)),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.equipement')),
                ('rapport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.rapport')),
            ],
        ),
        migrations.CreateModel(
            name='Sauvegarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janvier', models.FloatField(blank=True, null=True)),
                ('fevrier', models.FloatField(blank=True, null=True)),
                ('mars', models.FloatField(blank=True, null=True)),
                ('avril', models.FloatField(blank=True, null=True)),
                ('mai', models.FloatField(blank=True, null=True)),
                ('juin', models.FloatField(blank=True, null=True)),
                ('equipement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.equipement')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomLocal', models.CharField(max_length=500)),
                ('typeLocal', models.CharField(blank=True, max_length=500, null=True)),
                ('surface', models.FloatField(blank=True, null=True)),
                ('minT', models.FloatField(blank=True, null=True)),
                ('maxT', models.FloatField(blank=True, null=True)),
                ('minH', models.FloatField(blank=True, null=True)),
                ('maxH', models.FloatField(blank=True, null=True)),
                ('etageZ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.etage')),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='zoneE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.zone'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='localId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.zone'),
        ),
    ]
