# Generated by Django 5.0.4 on 2024-06-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='modele',
        ),
    ]
