# Generated by Django 5.0.4 on 2024-05-20 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='batiment',
            table=None,
        ),
    ]
