# Generated by Django 5.0.4 on 2024-05-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_alter_batiment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
