# Generated by Django 5.0.4 on 2024-05-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_historiqueuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiqueuser',
            old_name='decision',
            new_name='change',
        ),
    ]
