# Generated by Django 5.0.4 on 2024-05-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_rename_decision_historiqueuser_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiqueuser',
            name='user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
