# Generated by Django 5.0.4 on 2024-05-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0006_alter_historiqueuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiqueuser',
            name='user',
        ),
        migrations.AddField(
            model_name='historiqueuser',
            name='numero',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
