# Generated by Django 5.0.4 on 2024-05-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_remove_historiqueuser_user_historiqueuser_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiqueuser',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
