# Generated by Django 5.0.4 on 2024-05-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_alter_historiqueuser_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='decision',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
