# Generated by Django 5.0.4 on 2024-05-24 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0009_rapport_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historique',
            name='dateDebut',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historiqueuser',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
