# Generated by Django 5.0.4 on 2024-05-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0010_alter_historique_datedebut_alter_historiqueuser_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='equipementDest',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
