# Generated by Django 5.0.4 on 2024-05-25 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_historique_equipementdest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipementArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('categorie', models.CharField(blank=True, max_length=500, null=True)),
                ('puissance', models.FloatField(blank=True, null=True)),
                ('zoneE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.zone')),
            ],
        ),
    ]
