# Generated by Django 5.0.4 on 2024-05-25 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_equipementarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipementarchive',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
