# Generated by Django 5.0.4 on 2024-05-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_equipementarchive_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='batiment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='etage',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
