# Generated by Django 5.0.4 on 2024-05-26 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0015_historiqueadbatiment_historiqueadetage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiqueadetage',
            name='localId',
        ),
        migrations.AddField(
            model_name='historiqueadetage',
            name='etageId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quickstart.zone'),
        ),
    ]
