# Generated by Django 5.0.4 on 2024-05-26 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0016_remove_historiqueadetage_localid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiqueadetage',
            name='etageId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quickstart.etage'),
            preserve_default=False,
        ),
    ]
