# Generated by Django 5.0.4 on 2024-05-29 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0017_alter_historiqueadetage_etageid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeActiviteLastYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempsDebut', models.DateTimeField()),
                ('tempsFin', models.DateTimeField(blank=True, null=True)),
                ('consommation', models.FloatField(blank=True, null=True)),
                ('Equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.equipement')),
            ],
        ),
    ]
